[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "nix-search"
version = "0.0.1"
requires-python = ">=3.12"
dependencies = ["pydantic", "pydantic-settings", "textual"]

[project.optional-dependencies]
test = ["pytest", "pytest-asyncio", "pytest-cov"]
lint = ["ruff"]

[project.scripts]
nix-search = "nixsearch.app:main"

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]
nixsearch = ["themes/*.tcss"]

[tool.ruff]
target-version = "py312"
line-length = 100
src = ["src"]

[tool.ruff.lint]
select = ["E", "F", "I", "W"]

[tool.pytest.ini_options]
testpaths = ["src/tests"]
asyncio_mode = "auto"
